CREATE TABLE IF NOT EXISTS public.applications (
    id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
    application_type text NOT NULL DEFAULT 'trainee'::text,
    name text NOT NULL,
    faculty text NOT NULL,
    student_id text NOT NULL UNIQUE,
    national_id text NOT NULL UNIQUE,
    student_level text NOT NULL,
    telephone text NOT NULL,
    address text,
    has_laptop boolean DEFAULT false,
    codeforces_profile text,
    leetcode_profile text,
    leetcode_data jsonb,
    codeforces_data jsonb,
    scraping_status text DEFAULT 'pending'::text,
    ip_address text,
    user_agent text,
    email text,
    submitted_at timestamp with time zone DEFAULT now(),
    telegram_username text,
    email_hash character varying,
    email_blind_index text,
    national_id_blind_index text,
    telephone_blind_index text,
    student_id_blind_index text,
    CONSTRAINT applications_pkey PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS public.users (
    id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
    email text NOT NULL UNIQUE,
    password_hash text NOT NULL,
    application_id bigint,
    is_verified boolean DEFAULT false,
    last_login_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now(),
    profile_picture_url text,
    telegram_username text,
    role text DEFAULT 'trainee'::text,
    profile_visibility text DEFAULT 'public'::text,
    codeforces_data jsonb,
    codeforces_handle text,
    is_shadow_banned boolean DEFAULT false,
    cheating_flags integer DEFAULT 0,
    show_on_cf_leaderboard boolean DEFAULT true,
    show_on_sheets_leaderboard boolean DEFAULT true,
    show_public_profile boolean DEFAULT true,
    profile_picture character varying,
    email_blind_index text,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_application_id_fkey FOREIGN KEY (application_id) REFERENCES public.applications(id)
);